import Head from "next/head";
import Header from "../src/components/Header";
import Footer from "../src/components/Footer";
import Confirmacion from "../src/components/Confirmacion";

export default function ConfirmacionIndex() {
  return (
    <>
      <Head>
        <title>Innate Cita confirmacion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Confirmacion></Confirmacion>
      <Footer />
    </>
  );
}
