import Head from "next/head";
import Header from "../src/components/Header";
import CrearPerfilForm from "../src/components/CrearPerfilForm";
import Footer from "../src/components/Footer";

export default function Pago() {
  return (
    <>
      <Head>
        <title>Innate - Pago citas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <CrearPerfilForm></CrearPerfilForm>
      <Footer />
    </>
  );
}
