import Head from "next/head";
import Header from "../src/components/Header";
import FormPago from "../src/components/FormPago";
import Footer from "../src/components/Footer";

export default function Pago({ precio, router }) {
  return (
    <>
      <Head>
        <title>Innate - Pago citas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <FormPago precio={precio} router={router}></FormPago>
      <Footer />
    </>
  );
}

Pago.getInitialProps = async (context) => {
  return {
    router: context,
  };
};
